address_book_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('contacts/new/', views.AddressBookCreateView.as_view(), name='address-book'),
    path('', views.AddressBookListRecords.as_view(), name='list-records'),
    path('contacts/<int:pk>/', views.AddressBookRecordDetailView.as_view(), name='watch-contact'),
    path('contacts/<int:pk>/edit', views.EditContactView.as_view(), name='edit-contact'),
    path('contacts/<int:pk>/delete/', views.DeleteContactView.as_view(), name='delete-contact'),
]

main/models.py
from django.db import models


from django_countries.fields import CountryField


class AddressBook(models.Model):
    image = models.ImageField(default='default.jpg', upload_to='contact_pics', blank=True, null=True)
    first_name = models.CharField(max_length=100, unique=False, db_column='First name')
    last_name = models.CharField(max_length=100, unique=False, db_column='Last name')
    country = CountryField(blank=True)
    city = models.CharField(blank=True, max_length=100, unique=False, db_column='City')
    street = models.CharField(blank=True, max_length=100, unique=False, db_column='Street')
    phone_number = models.CharField(blank=True, max_length=20, db_column='Phone number')
    url = models.URLField(blank=True, db_column='URL')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['first_name', 'last_name'], name='unique fullname')
        ]
        ordering = ('first_name', 'last_name', )

    def __str__(self):
        return f'First name: {self.first_name}, ' \
               f'Last name: {self.last_name},'

main/forms.py
import re

from django import forms
from django.core.validators import URLValidator
from django.core.validators import ValidationError

from django_countries.widgets import CountrySelectWidget

from .models import AddressBook


def validate_phone_number(form_phone_number):
    if not re.match(r"^\d{8,15}$", form_phone_number):
        raise ValidationError(f'{form_phone_number}: Enter digits only in phone number')


class AddressBookForm(forms.ModelForm):
    url = forms.CharField(label='URL', required=False, validators=[URLValidator])
    phone_number = forms.CharField(label='Phone number', required=False, validators=[validate_phone_number])
    image = forms.ImageField(label='Image', required=False)

    class Meta:
        model = AddressBook
        fields = ('first_name', 'last_name', 'country', 'city', 'street', 'phone_number', 'url', 'image')
        widgets = {'country': CountrySelectWidget(),
                   'city': forms.TextInput(attrs={'placeholder': 'Optional'}),
                   'street': forms.TextInput(attrs={'placeholder': 'Optional'})}

main/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from .filters import AddressBookFilter
from .forms import AddressBookForm
from .models import AddressBook


class AddressBookCreateView(SuccessMessageMixin, CreateView):
    template_name = 'main/address_book_form.html'
    form_class = AddressBookForm
    success_message = 'Record saved successfully!'

    @transaction.atomic
    def form_valid(self, form):
        AddressBook.objects.create(**form.cleaned_data)
        return redirect('list-records')


class AddressBookListRecords(ListView):
    model = AddressBook
    template_name = 'main/address_book_list.html'
    paginate_by = 10
    filterset_class = AddressBookFilter

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset
        return context


class AddressBookRecordDetailView(DetailView):
    model = AddressBook
    template_name = 'main/address_book_detail.html'
    context_object_name = 'address_book'
    queryset = AddressBook.objects.all()

    def get_object(self, **kwargs):
        pk_ = self.kwargs.get("pk")
        return get_object_or_404(AddressBook, pk=pk_)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['update_form'] = AddressBookForm()
        return context


class EditContactView(UpdateView):
    model = AddressBook
    template_name = 'main/address_book_edit.html'
    form_class = AddressBookForm
    success_url = '/'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # def get_success_url(self):
    #     return reverse('watch-contact', kwargs={'pk': self.object.pk})


class DeleteContactView(DeleteView):
    model = AddressBook
    success_url = reverse_lazy('list-records')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

main/templates/main/address_book_detail.html
{% extends 'base.html' %}
{% block head %}
    <title>{{ address_book.first_name }} {{ address_book.last_name }}</title>
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="col-md-7">
        <div class="card p-3 py-4">
            <div class="text-center">
                 <img src="{{ address_book.image }}" width="200" height="200" alt="">
            </div>
            <div class="text-lg-left">
                <ul>
                    <li><h4>Fullname: {{ address_book.first_name }} {{ address_book.last_name }}</h4></li>
                    <li><h4>Country: {{ address_book.country.name }}</h4></li>
                    <li><h4>City: {{ address_book.city }}</h4></li>
                    <li><h4>Address: {{ address_book.street }}</h4></li>
                    <li><h4>Phone number: {{ address_book.phone_number }}</h4></li>
                    <li><h4>URL: {{ address_book.url }}</h4></li>

                </ul>
                <div class="text-center">
                    <a href="{{ request.META.HTTP_REFERER }}"><button class="btn btn-secondary px-4">Go Back</button></a>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/address_book_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head %}
    <title>Edit contact</title>
{% endblock %}
{% block content %}
    <h1>Edit contact</h1>
    <form action="{% url 'edit-contact' object.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
            {% for key, value in form.errors.items %}
                <div class="alert alert-error col-lg-12">
                    {{ value | striptags }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="form-row">
            <div class="form-group col-sm-3">
                {{ form.first_name|as_crispy_field }}
            </div>
            <div class="form-group col-sm-3">
                {{ form.last_name|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-3">
                {{ form.phone_number|as_crispy_field }}
            </div>
            <div class="col-sm-3">
                {{ form.url|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-2">
                {{ form.country|as_crispy_field }}
            </div>
            <div class="col-sm-2">
                {{ form.city|as_crispy_field }}
            </div>
            <div class="col-sm-2">
                {{ form.street|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-3">
                {{ form.image|as_crispy_field }}
            </div>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Update contact</button>
    </form>
{% endblock %}

main/templates/main/address_book_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head %}
    <title>Address Book Form</title>
{% endblock %}
{% block content %}
    <h1>Add record to address book</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
            {% for key, value in form.errors.items %}
                <div class="alert alert-error col-lg-12">
                    {{ value | striptags }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="form-row">
            <div class="form-group col-sm-3">
                {{ form.first_name|as_crispy_field }}
            </div>
            <div class="form-group col-sm-3">
                {{ form.last_name|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-3">
                {{ form.phone_number|as_crispy_field }}
            </div>
            <div class="col-sm-3">
                {{ form.url|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-2">
                {{ form.country|as_crispy_field }}
            </div>
            <div class="col-sm-2">
                {{ form.city|as_crispy_field }}
            </div>
            <div class="col-sm-2">
                {{ form.street|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-3">
                {{ form.image|as_crispy_field }}
            </div>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Create record</button>
    </form>


{% endblock %}

main/templates/main/address_book_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head %}
    <title>All records</title>
    {{ block.super }}
{% endblock %}
{% block content %}
    <br><br/>
    <a href="{% url 'address-book' %}"><button class="btn btn-primary">Add more records</button></a>
    <form method="GET">
        {{ filter.form|crispy }}
            <button type="submit" class="btn btn-secondary">Search</button>
    <br><br/>
    </form>
    <table class="table table-striped table-bordered table-hover">
        <thead class="thead-dark">
            <th scope="col">ID</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Country</th>
            <th scope="col">City</th>
            <th scope="col">Address</th>
            <th scope="col">Link</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </thead>
        <tbody>
            {% for record in addressbook_list %}
                <tr>
                    <td>{{ record.id|safe }}</td>
                    <td>{{ record.first_name }}</td>
                    <td>{{ record.last_name }}</td>
                    <td>{{ record.country }}</td>
                    <td>{{ record.city }}</td>
                    <td>{{ record.street }}</td>
                    <td><a href="{% url 'watch-contact' record.pk %}">Show details</a></td>
                    <td><a href="{% url 'edit-contact' record.pk%}">Edit</a></td>
                    <td><a href="{% url 'delete-contact' record.pk%}">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <br><br/>

    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
          crossorigin="anonymous">


    {% load static %}
    {% block head %}
    <title>Title</title>
    {% endblock %}
</head>
<body>
    <div class="container-fluid">
        {% block content %}
        {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous">

</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous">
</script>
</body>
</html>